export const POSTDARE = 'POSTDARE';
export const MATCHEDDARE = 'MATCHEDDARE';
export const PENDINGDARE = 'PENDINGDARE';
export const ACCEPTDARE = 'ACCEPTDARE';
export const DECLINEDARE = 'DECLINEDARE';
export const FAILEDTODARE = 'FAILEDTODARE';

export const NODARE = 'NO-DARE';
export const QUEUE = 'QUEUE';
export const USERMATCH = 'USER-MATCH';
export const MATCHEDPENDING = 'MATCHED-PENDING';
export const MATCHEDACCEPTED = 'MATCH-ACCEPTED';
export const STATUSFAILED = 'STATUS-FAILED';