export const POSTDARE = 'POSTDARE';
export const MATCHEDDARE ='MATCHEDDARE';
export const PENDINGDARE = 'PENDINGDARE';

export const ACCEPTDARE = 'ACCEPTDARE';
export const DECLINEDARE = 'DECLINEDARE';

export const FAILEDTODARE = 'FAILEDTODARE';
